image: aursu/rpmbuild:7.9.2009-docker

stages:
  - base
  - build1
  - build2
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  OS7: 7.9.2009
  OS7TAG: 7.9.2009
  RL8: 8.8.20230518
  RL8TAG: 8.8.20230518
  CI_COMMIT_SHORT_SHA_RL8: ${CI_COMMIT_SHORT_SHA}-rocky-8

centos7base:
  stage: base
  variables:
    BASE: centos7base
  script:
    - docker volume create $CI_COMMIT_SHORT_SHA
    - docker-compose -f docker-compose.base.yml build --no-cache --pull $BASE

rocky8base:
  stage: base
  variables:
    BASE: rocky8base
  script:
    - docker volume create $CI_COMMIT_SHORT_SHA_RL8
    - docker-compose -f docker-compose.base.yml build --no-cache --pull $BASE

centos7kernelonly:
  stage: build1
  timeout: 3h
  variables:
    BUILD: centos7kernelonly
  script:
    - docker-compose build --no-cache $BUILD
    - docker-compose run -v $CI_COMMIT_SHORT_SHA:/home/centos/rpmbuild/RPMS $BUILD
    - docker-compose rm -f -v

rocky8kernelonly:
  stage: build2
  timeout: 3h
  variables:
    BUILD: rocky8kernelonly
  script:
    - docker-compose build --no-cache $BUILD
    - docker-compose run -v $CI_COMMIT_SHORT_SHA_RL8:/home/centos/rpmbuild/RPMS $BUILD
    - docker-compose rm -f -v

centos7deploy:
  stage: deploy
  variables:
    FTPTRAY_USER: centos-7
    FTPTRAY_REPO: local
  script:
    - docker run --rm -v $CI_COMMIT_SHORT_SHA:/home/centos/rpmbuild/RPMS -e FTPTRAY_USER=$FTPTRAY_USER -e FTPTRAY_PASSWORD=$FTPTRAY_PASSWORD -e FTPTRAY_REPO=$FTPTRAY_REPO -e FTPTRAY_HOST=$FTPTRAY_HOST aursu/rpmbuild:ftptray /usr/local/bin/ftptray.py /home/centos/rpmbuild/RPMS

rocky8deploy:
  stage: deploy
  variables:
    FTPTRAY_USER: rocky-8
    FTPTRAY_REPO: local
  script:
    - docker run --rm -v $CI_COMMIT_SHORT_SHA_RL8:/home/centos/rpmbuild/RPMS -e FTPTRAY_USER=$FTPTRAY_USER -e FTPTRAY_PASSWORD=$FTPTRAY_PASSWORD -e FTPTRAY_REPO=$FTPTRAY_REPO -e FTPTRAY_HOST=$FTPTRAY_HOST aursu/rpmbuild:ftptray /usr/local/bin/ftptray.py /home/centos/rpmbuild/RPMS
