image: ghcr.io/aursu/rpmbuild:10.1.20251126-docker-29.4.0

stages:
  - base
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  RL8: 8.10.20240528
  RL8TAG: 8.10.20240528
  RL9: 9.7.20251123
  RL9TAG: 9.7.20251123
  CI_COMMIT_SHORT_SHA_RL8: ${CI_COMMIT_SHORT_SHA}-rocky-8
  CI_COMMIT_SHORT_SHA_RL9: ${CI_COMMIT_SHORT_SHA}-rocky-9

rocky9base:
  stage: base
  variables:
    BASE: rocky9base
  script:
    - docker volume create $CI_COMMIT_SHORT_SHA_RL9
    - docker compose -f docker-compose.base.yml build --no-cache --pull $BASE

rocky9kernelonly:
  stage: build
  timeout: 3h
  variables:
    BUILD: rocky9kernelonly
  script:
    - docker compose build --no-cache $BUILD
    - docker compose run -v $CI_COMMIT_SHORT_SHA_RL9:/home/centos/rpmbuild/RPMS $BUILD

rocky9deploy:
  stage: deploy
  variables:
    FTPTRAY_USER: rocky-9
    FTPTRAY_REPO: custom
  script:
    - docker run --rm -v $CI_COMMIT_SHORT_SHA_RL9:/home/centos/rpmbuild/RPMS -e FTPTRAY_USER=$FTPTRAY_USER -e FTPTRAY_PASSWORD=$FTPTRAY_PASSWORD -e FTPTRAY_REPO=$FTPTRAY_REPO -e FTPTRAY_HOST=$FTPTRAY_HOST aursu/rpmbuild:ftptray /usr/local/bin/ftptray.py /home/centos/rpmbuild/RPMS
