language: minimal

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - PACKAGE_VCS_URL=https://gitlab.com/aursu/rpmbuild-kernel.git
    - BINTRAY_REPO=custom

jobs:
  include:
    - stage: test
      install:
        - docker-compose -f docker-compose.base.yml build --no-cache --pull ${BASE}
      before_script:
        - docker-compose build --no-cache ${BUILD}
      script:
        - docker-compose up --exit-code-from ${BUILD} ${BUILD}
      before_deploy:
        - docker-compose -f rpmbuild/docker-compose.bintray.yml pull ${UPLOADER}
      deploy:
        provider: script
        script:
          - docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm -e BINTRAY_USER=$BINTRAY_USER -e BINTRAY_API_KEY=$BINTRAY_API_KEY -e BINTRAY_REPO=$BINTRAY_REPO -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL ${UPLOADER}
        on:
          all_branches: true
      env: BASE=centos7base BUILD=centos7kernelonly UPLOADER=centos7bintray
