language: minimal

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - ARTIFACTORY_URL=https://rpmb.jfrog.io
    - BINTRAY_REPO=custom
    - OS7=7.9.2009
    - OS8=8.3.2011
    - OS7TAG=7.9.2009
    - OS8TAG=8.3.2011

jobs:
  include:
    - stage: test
      install:
        - docker-compose -f docker-compose.base.yml build --no-cache --pull ${BASE}
      before_script:
        - docker-compose build --no-cache ${BUILD}
      script:
        - docker-compose up --exit-code-from ${BUILD} ${BUILD}
      before_deploy:
        - docker-compose -f rpmbuild/docker-compose.bintray.yml pull ${UPLOADER}
      deploy:
        provider: script
        script:
          - docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm -e BINTRAY_USER=$BINTRAY_USER -e BINTRAY_API_KEY=$BINTRAY_API_KEY -e BINTRAY_REPO=$BINTRAY_REPO -e ARTIFACTORY_URL=$ARTIFACTORY_URL ${UPLOADER}
        on:
          all_branches: true
      env: BASE=centos7base BUILD=centos7kernelonly UPLOADER=centos7bintray
