# image comes from rpmbuild-libtool project
ARG os=9.7.20251123
FROM aursu/rpmbuild:${os}-build

USER root
RUN dnf -y install \
        asciidoc \
        audit-libs-devel \
        bc \
        bindgen \
        binutils-devel \
        bpftool \
        clippy \
        dwarves \
        elfutils-devel \
        gcc-plugin-devel \
        gettext \
        glibc-static \
        hmaccalc \
        hostname \
        java-devel \
        kmod \
        libcap-devel \
        libcap-ng-devel \
        ncurses-devel \
        net-tools \
        newt-devel \
        numactl-devel \
        openssl \
        openssl-devel \
        pciutils-devel \
        perl-devel perl-generators "perl(ExtUtils::Embed)" \
        pesign \
        python3-devel python3-docutils python3-pyyaml \
        rust rust-src rustfmt \
        kernel-rpm-macros \
        system-sb-certs \
        xmlto \
        xz-devel \
        zlib-devel \
    && dnf clean all && rm -rf /var/cache/dnf