version: "3.4"
services:
  centos7base:
    build:
      context: .
      dockerfile: Dockerfile.7-base
      args:
        centos: $OS7
    image: "aursu/rpmbuild:${OS7}-base-kernel"
  stream8base:
    build:
      context: .
      dockerfile: Dockerfile.stream8-base
    image: aursu/rpmbuild:stream8-base-kernel