version: "3"
services:
  centos7base:
    build:
      context: .
      dockerfile: Dockerfile.7-base
      args:
        centos: $OS7
    image: "aursu/rpmbuild:${OS7}-base-kernel"
  rocky8base:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        os: $RL8
    image: "aursu/rpmbuild:${RL8TAG}-base-kernel"