version: "3.4"
services:
  centos7kerneltest:
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - rpm7:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        centos: $OS7
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    tmpfs:
      - /run

volumes:
  rpm7:
    name: rpm7
